language: python
python:
  - '2.7'
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
env:
  global:
    - GH_REF: github.com/loa/ppl-pocket.git
    - secure: cdFz8PDJ9ZyXTOwIu/PF6zXjIaW/HPbmg1dL8Fb+/x6/EXQW1YyyRk6eQqf4hGHs6GeGIDIE3oi0cSW0xAtZR3Xl344dqinmGiBD9SjtzVcAHmFfWZturX0ZzTzowNsBm1awenFxLgWL2o3Iza2AO3tvCG05cG0AKl4EQgKVMr0=
script: |
    make html
    cd build/html
    echo "ppl-pocket.com" > CNAME
    git init
    git config user.name "Travis CI"
    git config user.email "notifications@travis-ci.org"
    touch .nojekyll
    git add .
    git commit -m "Deploy to Github Pages"
    git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
